insert.config:
  type: config_object
  label: 'Insert module configuration settings'
  mapping:
    text_formats:
      type: sequence
      label: 'Automatic text format support'
      sequence:
        type: string
    absolute:
      type: boolean
      label: 'Use absolute paths'
    file_field_images_enabled:
      type: boolean
      label: 'Allow inserting <img> tags for images uploaded to generic file fields'
    widgets:
      type: mapping
      label: 'Lists of field widget ids that Insert should be available to'
      mapping:
        file:
          type: sequence
          label: 'List of file field widgets ids that Insert should be available to'
          sequence:
            type: string
        image:
          type: sequence
          label: 'List of image field widgets ids that Insert should be available to'
          sequence:
            type: string
    css_classes:
      type: mapping
      label: 'Additional CSS classes to be added to items inserted using the Insert module'
      # The mapping keys map to field type names.
      mapping:
        file:
          type: sequence
          label: 'CSS classes to be added to generic file links'
          sequence:
            type: string
        image:
          type: sequence
          label: 'CSS classes to be added to images and image links'
          sequence:
            type: string
    file_extensions:
      type: mapping
      label: 'File extensions used for file type detection'
      mapping:
        audio:
          type: sequence
          label: 'Audio file extensions'
          sequence:
            type: string
        video:
          type: sequence
          label: 'Video file extensions'
          sequence:
            type: string
