id: d7_insert_colorbox_settings
label: Insert Colorbox settings
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - colorbox_image_style
    - colorbox_insert_gallery
  source_module: colorbox
process:
  style: colorbox_image_style
  gallery:
    plugin: static_map
    source: colorbox_insert_gallery
    map:
      0: 'page'
      3: '0'
destination:
  plugin: config
  config_name: insert_colorbox.config
