insert_colorbox.config:
  type: config_object
  label: 'Insert Colorbox module configuration settings'
  mapping:
    style:
      type: string
      label: 'Image style to be applied to images viewed in the colorbox'
    gallery:
      type: string
      label: 'Whether to use a particular gallery aggregating the colorbox images'
